#!/usr/bin/env node

/**
 * Setup script for Daylite Conference Room Display
 * Helps obtain and configure API tokens
 */

const readline = require('readline');
const fs = require('fs').promises;
const path = require('path');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

const question = (query) => new Promise((resolve) => rl.question(query, resolve));

async function setup() {
  console.log('🚀 Daylite Conference Room Display Setup Wizard 🚀');

  console.log('This wizard will help you set up your Daylite API tokens.\n');
  console.log('You\'ll need to get these from your Daylite API dashboard.');
  console.log('Visit: https://developer.daylite.app/reference/personal-token\n');


  console.log('\n🔐 Enter your tokens:\n');
  
  const accessToken = await question('Access Token: ');
  const refreshToken = await question('Refresh Token: ');
  
  console.log('\n🌐 Server configuration:\n');
  const port = await question('Port number (default: 8080): ') || '8080';

  // Create .env file
  let envContent = `# Daylite API Configuration
# Generated by setup wizard on ${new Date().toISOString()}

# Daylite Personal Access Token (expires in 1 hour, auto-refreshes)
DAYLITE_ACCESS_TOKEN=${accessToken}

# Daylite Refresh Token (used for automatic token renewal)
DAYLITE_REFRESH_TOKEN=${refreshToken}

# Server Configuration
PORT=${port}
`;

  try {
    await fs.writeFile('.env', envContent);
    console.log('\n✅ Configuration saved to .env file');
    
    // Test the connection
    console.log('\n🔍 Testing connection to Daylite API...');
    
    const testUrl = 'https://api.marketcircle.net/v1/appointments?limit=1';
    const response = await fetch(testUrl, {
      headers: {
        'Authorization': `Bearer ${accessToken}`,
        'Accept': 'application/json'
      }
    });
    
    if (response.ok) {
      console.log('✅ Successfully connected to Daylite API!');
    } else if (response.status === 401) {
      console.log('⚠️  Access token may be expired. The app will automatically refresh it on startup.');
    } else {
      console.log(`⚠️  Received status ${response.status}. Please check your tokens.`);
    }
    
  } catch (error) {
    console.error('❌ Error:', error.message);
  }

  console.log('\n📱 Setup complete! You can now run:');
  console.log('   npm start        - Start the server');
  console.log('   npm run dev      - Start in development mode\n');
  console.log('Then open http://localhost:' + port + ' in your browser\n');

  rl.close();
}

// Run setup
setup().catch(error => {
  console.error('Setup failed:', error);
  rl.close();
  process.exit(1);
});
